server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100000000
      maxRequestSize: 200000000
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
    #url: bolt://localhost:7687  #3.x
    url: neo4j://localhost:7687
    username: neo4j
    password: 123456
  datasource:
    url: jdbc:mysql://rm-uf649ipw0c2fdok97xo.mysql.rds.aliyuncs.com:3306/kg?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: tan
    password: tan!@#123
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  typeAliasesPackage: com.warmer.web.model
  mapperLocations: classpath*:/mapping/*.xml
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#--------七牛云配置
qiniu:
  access:
    key: GpiK0MFBKXufgOOmxXIAnrHZ6sUcDwlpOb5xDM3c
  secret:
    key: OqjCQj9nm2H5P_vaqjbfY9xP_GT54aSWWcCA8pgS
  bucket:
    name: nndt
    host:
      name: file.miaoleyan.com
  prefixName: /nndt
#--------七牛云配置
img:  #//如果是Windows情况下，格式是 D:\\blog\\image\\   linx 格式"/home/blog/image/";
  location : /home/blog/image/
file:
  serverurl:  http://localhost:8089
  location : /home/kgmanager/csv/   #如果是Windows情况下，格式是 D:\\kgmanager\\csv\\   linx 格式"/home/kgmanager/csv/";